const fs = require('fs');

// Subdivision to State mapping
const SUB_TO_STATES = {
  'ANDAMAN & NICOBAR ISLANDS': ['ANDAMAN And NICOBAR ISLANDS'],
  'ARUNACHAL PRADESH': ['ARUNACHAL PRADESH'],
  'ASSAM & MEGHALAYA': ['ASSAM', 'MEGHALAYA'],
  'NAGA MANI MIZO TRIPURA': ['NAGALAND', 'MANIPUR', 'MIZORAM', 'TRIPURA'],
  'SUB HIMALAYAN WEST BENGAL & SIKKIM': ['WEST BENGAL', 'SIKKIM'],
  'GANGETIC WEST BENGAL': ['WEST BENGAL'],
  'ORISSA': ['ORISSA'],
  'JHARKHAND': ['JHARKHAND'],
  'BIHAR': ['BIHAR'],
  'EAST UTTAR PRADESH': ['UTTAR PRADESH'],
  'WEST UTTAR PRADESH': ['UTTAR PRADESH'],
  'UTTARAKHAND': ['UTTARANCHAL'],
  'HARYANA DELHI & CHANDIGARH': ['HARYANA', 'DELHI', 'CHANDIGARH'],
  'PUNJAB': ['PUNJAB'],
  'HIMACHAL PRADESH': ['HIMACHAL'],
  'JAMMU & KASHMIR': ['JAMMU AND KASHMIR'],
  'WEST RAJASTHAN': ['RAJASTHAN'],
  'EAST RAJASTHAN': ['RAJASTHAN'],
  'WEST MADHYA PRADESH': ['MADHYA PRADESH'],
  'EAST MADHYA PRADESH': ['MADHYA PRADESH'],
  'GUJARAT REGION': ['GUJARAT', 'DADAR NAGAR HAVELI', 'DAMAN AND DUI'],
  'SAURASHTRA & KUTCH': ['GUJARAT'],
  'KONKAN & GOA': ['GOA', 'MAHARASHTRA'],
  'MADHYA MAHARASHTRA': ['MAHARASHTRA'],
  'MATATHWADA': ['MAHARASHTRA'],
  'VIDARBHA': ['MAHARASHTRA'],
  'CHHATTISGARH': ['CHATISGARH'],
  'COASTAL ANDHRA PRADESH': ['ANDHRA PRADESH'],
  'TELANGANA': ['TELANGANA'],
  'RAYALSEEMA': ['ANDHRA PRADESH'],
  'TAMIL NADU': ['TAMIL NADU', 'PONDICHERRY'],
  'COASTAL KARNATAKA': ['KARNATAKA'],
  'NORTH INTERIOR KARNATAKA': ['KARNATAKA'],
  'SOUTH INTERIOR KARNATAKA': ['KARNATAKA'],
  'KERALA': ['KERALA'],
  'LAKSHADWEEP': ['LAKSHADWEEP']
};

console.log('Subdivision mapping defined.');
